language: python
python:
  - 2.7
  - pypy
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libmemcached-dev
  - pip install -r requirements.txt
services:
  - memcached
script:
  - python app_test.py
